### ISSUE TITLE
Allow players to leave a game

### ISSUE THREAD

**Issue by toanhminh0412** [toanhminh0412/soccer_app#12]

**Comment by toanhminh0412** [comment]
1. Ben:
- Design a lower nav in the game detail page that contains two buttons next to each other. One of them is "leave game". The button has to be hoverable, background color should be white

**Comment by benlehuyvy176** [comment]
[
![image](https://user-images.githubusercontent.com/71539951/210022971-64257de0-a82d-4f94-a16a-16cf11de6783.png)
](url)

**Comment by benlehuyvy176** [comment]
Should I write the function for the **Leave Game** button?

**Comment by toanhminh0412** [comment]
Looking good. I say go for it
